import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import styles1 from "../styles/Home1.module.css";
import Script from "next/script";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
    <style jsx >
      {`
        .span1{
        color: green;
        }
      `}
    </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={`${styles.mainNav} ${styles1.con}`}> 
          <ul>
          <Link href=""><li>Home</li></Link>
           <Link href="/about"> <li>About</li></Link>
           <Link href="/blog"> <li>Blog</li></Link>
           <Link href="/contact"> <li>Contact</li></Link>
          </ul>
        </nav>
      <main className={`${styles.main} ${inter.className}`}>
    
        <div>
        <h1 className={styles.center}>
        <span className="span1">Hunting Coder</span>
        </h1>
            <p className={styles.center} >
              A Blog for Hunting Coder By a hunting coder
            </p>
            <h2  className={styles.center}>Popular Blogs</h2>
            </div>
            <div className="blog">
              <div className="blogItems">
                <h3>How to Learn javascript in 2024?</h3>
                <p>This is a blog to learn javascript from starting to advance</p>
              </div>
            </div>
            <div className="blog">
              <div className="blogItems">
                <h3>How to Learn javascript in 2024?</h3>
                <p>This is a blog to learn javascript from starting to advance</p>
              </div>
            </div>
            <div className="blog">
              <div className="blogItems">
                <h3>How to Learn javascript in 2024?</h3>
                <p>This is a blog to learn javascript from starting to advance</p>
              </div>
            </div>
            <div className="blog">
              <div className="blogItems">
                <h3>How to Learn javascript in 2024?</h3>
                <p>This is a blog to learn javascript from starting to advance</p>
              </div>
            </div>
      </main>
    </>
  );
}
