import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="/sc.js"></Script>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
        <h1 className={styles.center}>
        Hunting Coder
        </h1>
            <p >
              A Blo for Hunting Coder By a hunting coder
            </p>
            </div>
      </main>
    </>
  );
}
